### ISSUE TITLE
Linja failed to install Ninja

### ISSUE THREAD

**Issue by soonhokong** [leanprover/lean#285]
```
Building CXX object shell/CMakeFiles/lean.dir/lean.cpp.o
Linking CXX executable lean_scanner
Linking CXX executable lean
[100%] Built target lean_scanner
[100%] Built target lean
Traceback (most recent call last):
  File "/home/cdr1454/prog/cpp/lean/src/../bin/linja", line 638, in <module>
    sys.exit(main())
  File "/home/cdr1454/prog/cpp/lean/src/../bin/linja", line 623, in main
    return call_ninja(args)
  File "/home/cdr1454/prog/cpp/lean/src/../bin/linja", line 429, in call_ninja
    proc = subprocess.Popen([g_ninja_path] + ninja_option + targets, stdout=proc_out, stderr=proc_err)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
make[2]: *** [CMakeFiles/standard_lib] Error 1
make[1]: *** [CMakeFiles/standard_lib.dir/all] Error 2
make: *** [all] Error 2
```

@codyroux reported the problem.

**Comment by soonhokong** [comment]
`OSError: [Errno 8] Exec format error` normally indicates that the binary is not compatible with the system's architecture. However, I've checked that @codyroux is using x86_64 architecture machine (Ubuntu, Linux kernel 3.13.0-37). It shouldn't be the binary compatibility problem.

It seems that the problem is triggered by the company's firewall. We agreed to close this issue since he can install `ninja` via `apt-get` and is able to use Lean without a problem.
